[project]
name = "Music-Project"
version = "0.1.0"
description = "Just trying to be a better recommender"
requires-python = ">=3.11"
dependencies = [
    "pandas",
    "psycopg2-binary",
    "python-dotenv",
    "datasets",
    "huggingface-hub",
    "torch",
    "torchaudio",
]


[build-system]
requires = ["uv_build>=0.12.13,<0.13.0"]
build-backend = "uv_build"

[tool.uv.sources]
torch = [
  { index = "pytorch-cpu", marker = "sys_platform == 'darwin'" },
  { index = "pytorch-cu121", marker = "sys_platform == 'win32'" },
]
torchaudio = [
  { index = "pytorch-cpu", marker = "sys_platform == 'darwin'" },
  { index = "pytorch-cu121", marker = "sys_platform == 'win32'" },
]

[[tool.uv.index]]
name = "pytorch-cpu"
url = "https://download.pytorch.org/whl/cpu"
explicit = true

[[tool.uv.index]]
name = "pytorch-cu121"
url = "https://download.pytorch.org/whl/cu121"
explicit = true
